version: "3.8"
services:
    database:
        container_name: database
        image: postgres:15.5-alpine
        env_file:
            - .env
        volumes:
            - itss-db:/data/postgres
            - itss-db:/var/lib/postgresql/data
            - ./database:/docker-entrypoint-initdb.d
        restart: unless-stopped
        ports:
            - "5432:5432"
        networks:
            - itss-net

    backend:
        container_name: backend
#        build: .
        volumes:
            -   ./:/app
            -  /app/node_modules
        env_file:
            - .env
        command: npm start
        ports:
            - "80:80"
        image: tungnguyensnk/itss:dev
        networks:
            - itss-net
        depends_on:
            - database
networks:
    itss-net:
        driver: bridge

volumes:
    itss-db:
        driver: local
